# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import json
from typing import Any, List

from pydantic import BaseModel
from .generated_media import GeneratedMedia


class RetrieveAssetAgentRequest(BaseModel):
    """
    This schema is used to represent a Request tp RetrieveAssetAgent
    """
    
    command: str
    required_mimetype: str
    call_rationale: str
    full_context: str
    generated_videos: List[Any] | None
    generated_images: List[Any] | None
    
    
    @property
    def prompt(self):
        # 1. Get the schema as a dictionary
        schema_dict = GeneratedMedia.model_json_schema()

        # 2. Convert the dictionary to a formatted JSON string
        schema_string = json.dumps(schema_dict, indent=2)

        agent_prompt = f"""
        You are being called as a fallback asset retrieval specialist.
        Your goal is to return a single asset that best matches the user's
        request, based on the context provided.

        **CRITICAL TASK:**
        1.  Analyze the 'Full Context' and 'User Command' to understand what 
            asset the user needs. I.e. if the context contains a specific asset 
            the user is referring to (e.g., "edit the image of the skier"), 
            find that asset.
        2.  The 'Call Rationale' explains why your parent agent was not able 
            to handle the user's request on its own.
        3.  The 'generated_videos' and 'generated_images' contain all the assets
            generated by the user throughout this session.
        4.  If no specific asset is mentioned, find the best *backup*
            asset from your available catalog that matches the 'User Command'.

        **User Command:**
        {self.command}

        **Full Context & Conversation History:**
        ---
        {self.full_context}
        ---

        **Reason for Fallback (Call Rationale):**
        {self.call_rationale}
        
        
        **REMINDER: Your entire response must be ONLY the JSON string of the media asset,
        like this example:**
        {schema_string}
        """
        
        return agent_prompt